<a href="https://colab.research.google.com/github/Kufala/Fraud-Detection/blob/main/Proj_1(tweets).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('Tweets.csv')

In [ ]:
df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [ ]:
import spacy

In [ ]:
nlp = spacy.load('en_core_web_sm')

NameError: name 'spacy' is not defined

In [ ]:
# df['new_text'] = df.text.apply(nlp) # create a new column new text that contains the tokenized text
df['new_text'] = list(nlp.pipe(iter(df['text']), n_process=-1))

In [ ]:
df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [ ]:
def process_text(text: str):
    """Takes a text, apply lemmatization, and remove stopwords and punctuations, remove special characters, numbers, URLs, mentions (@user), and hashtags (#topic) appropriately
    and vectorize the remaining text"""

    doc = nlp(text)

    filtered_tokens = [
        token.lemma_.lower() for token in doc if not token.is_punct and not token.is_stop
    ]

    processed_text = " ".join(filtered_tokens)

    if not processed_text:
        print("No meaningful token left.")
        return None

    process_doc = nlp(processed_text)

    if process_doc.has_vector:
        return process_doc.vector
    else:
        print("Process doc has no vextor")
        return None

In [ ]:
df['vector'] = df['text'].apply(process_text)

NameError: name 'df' is not defined

In [ ]:
df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone,new_text,vector
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada),"(@VirginAmerica, What, @dhepburn, said, .)","[-0.12706053, -0.6496554, -0.14925225, 0.24642..."
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada),"(@VirginAmerica, plus, you, 've, added, commer...","[-0.115148984, -0.39633903, -0.19230206, -0.11..."
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada),"(@VirginAmerica, I, did, n't, today, ..., Must...","[0.13119306, -0.8165495, 0.38030115, -0.563768..."
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada),"(@VirginAmerica, it, 's, really, aggressive, t...","[0.45216092, -0.6077622, -0.28926408, -0.17574..."
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada),"(@VirginAmerica, and, it, 's, a, really, big, ...","[0.874671, -0.3343607, -0.45704687, 0.05389751..."

In [ ]:
df[['vector', 'airline_sentiment']]

                                                  vector airline_sentiment
0      [-0.12706053, -0.6496554, -0.14925225, 0.24642...           neutral
1      [-0.115148984, -0.39633903, -0.19230206, -0.11...          positive
2      [0.13119306, -0.8165495, 0.38030115, -0.563768...           neutral
3      [0.45216092, -0.6077622, -0.28926408, -0.17574...          negative
4      [0.874671, -0.3343607, -0.45704687, 0.05389751...          negative
...                                                  ...               ...
14635  [0.20569234, -0.6579619, 0.4202623, -0.0197321...          positive
14636  [0.33202672, -0.45796955, 0.062018886, 0.15036...          negative
14637  [-0.014773977, -0.21706745, -0.9156133, 0.0182...           neutral
14638  [-0.13918199, -0.72086287, 0.30568522, 0.50809...          negative
14639  [0.28814965, -0.48892295, 0.4865672, 0.1672473...           neutral

[14640 rows x 2 columns]

In [ ]:
#Encode airline_sentiment column

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Initialize the LabelEncoder
le = LabelEncoder()

In [ ]:
# Fit and transform the airline_sentiment column
df['sentiment_encoded'] = le.fit_transform(df['airline_sentiment'])

In [ ]:
# Now your DataFrame has a new column 'sentiment_encoded' with integer labels
# Mapping (you can check it):
label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(label_mapping)

{'negative': np.int64(0), 'neutral': np.int64(1), 'positive': np.int64(2)}

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [ ]:
# Convert the 'vector' column to a feature matrix
X = df['vector'].tolist()
y = df['sentiment_encoded']

In [ ]:
#Split your data into training and testing sets (e.g., 80% training, 20% testing).
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
# Predictions
y_pred = clf.predict(X_test)

In [ ]:
# Classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.95      0.81      1889
           1       0.51      0.24      0.33       580
           2       0.71      0.19      0.30       459

    accuracy                           0.69      2928
   macro avg       0.65      0.46      0.48      2928
weighted avg       0.67      0.69      0.64      2928

In [ ]:
# Logistic Regression

In [ ]:

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
# Step 2: Prepare features and target
X = df['vector'].tolist()  # Convert Series of lists to list of lists
y = df['sentiment_encoded']

In [ ]:
# Step 3: Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Step 4: Train Logistic Regression
clf = LogisticRegression(max_iter=1000, solver='lbfgs', multi_class='multinomial')  # multinomial for multiclass
clf.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(max_iter=1000, multi_class='multinomial')

In [ ]:
# Step 5: Predictions & Evaluation
y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))

Accuracy: 0.7056010928961749

Classification Report:
               precision    recall  f1-score   support

    negative       0.74      0.93      0.82      1889
     neutral       0.50      0.27      0.35       580
    positive       0.64      0.34      0.44       459

    accuracy                           0.71      2928
   macro avg       0.63      0.51      0.54      2928
weighted avg       0.68      0.71      0.67      2928

In [ ]:
#Support Vector Machine (SVM)

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
#Step 2: Prepare features and target
X = df['vector'].tolist()  # list of lists
y = df['sentiment_encoded']

In [ ]:
# Step 3: Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
#Step 4: Optional - Feature scaling for SVM
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Step 5: Train SVM (RBF kernel is default)
svm_clf = SVC(kernel='rbf', C=1.0, gamma='scale')  # Use linear or poly if preferred
svm_clf.fit(X_train_scaled, y_train)

SVC()

In [ ]:
#Step 6: Predictions and Evaluation
y_pred = svm_clf.predict(X_test_scaled)

In [ ]:
#("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))

Classification Report:
               precision    recall  f1-score   support

    negative       0.73      0.95      0.83      1889
     neutral       0.55      0.26      0.35       580
    positive       0.75      0.28      0.41       459

    accuracy                           0.71      2928
   macro avg       0.68      0.50      0.53      2928
weighted avg       0.70      0.71      0.67      2928

In [ ]:
#Naive Bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
# Step 2: Prepare features and target
X = df['vector'].tolist()
y = df['sentiment_encoded']

In [ ]:
# Step 3: Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Step 4: Optional - Feature scaling (can help slightly with GaussianNB)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Step 5: Train Gaussian Naive Bayes
nb_clf = GaussianNB()
nb_clf.fit(X_train_scaled, y_train)

GaussianNB()

In [ ]:
# Step 6: Predictions and Evaluation
y_pred = nb_clf.predict(X_test_scaled)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))

Accuracy: 0.641051912568306

Classification Report:
               precision    recall  f1-score   support

    negative       0.74      0.82      0.78      1889
     neutral       0.41      0.33      0.36       580
    positive       0.39      0.31      0.34       459

    accuracy                           0.64      2928
   macro avg       0.51      0.48      0.49      2928
weighted avg       0.62      0.64      0.63      2928